### ISSUE TITLE
Create array of inverse colors

### ISSUE THREAD

**Issue by aec1140** [CoffeeFrame/SNAIL#14]
For the array of colors currently, create another array called `textColors` where `textColors[0]` is the inverse of `colors[0]`. Inverse should be the the colors value with each component -255 and %'d

**Comment by Awmusic12635** [comment]
Is this for the text color?

**Comment by aec1140** [comment]
Yes

**Comment by aec1140** [comment]
Also will be used for stroke color for highlighting

**Comment by Awmusic12635** [comment]
I pushed to the inverse branch, please let me know if this is what you wanted.

**Comment by aec1140** [comment]
yeah that looks good

**Comment by Awmusic12635** [comment]
Done
