### ISSUE TITLE
Highlighting of Selected index

### ISSUE THREAD

**Issue by aec1140** [CoffeeFrame/SNAIL#15]
* [x] Create an attribute for circle called `strokeColor` and initialize it to the `color` value
* [x] When the circle is selected in `doMouseDown` set the circles `strokeColor` to the `textColor`
* [x] In the drawCircle function in utilities, set the stroke color`ctx.strokeStyle = this.strokeColor` after the circle is filled and call `ctx.stroke()` to stroke the circle.

**Comment by aec1140** [comment]
Note: whomever does this may want to do the inverse colors first to avoid merge conflicts

**Comment by Awmusic12635** [comment]
I believe this should be completed in branch indexhighlight
