### ISSUE TITLE
Make sure circle clicked is next to the selected circle

### ISSUE THREAD

**Issue by aec1140** [CoffeeFrame/SNAIL#16]
currently you can click any two circles and they will be added. Need to check if the two circles are next to each other in the array.

**Comment by Awmusic12635** [comment]
Do you think it would be useful to have each circle know what its position in the array is? Might be useful for situations such as this. Could have it update on each draw so that it is always up to date.

**Comment by aec1140** [comment]
This shouldn't be too bad, just either check array[i-1][k] || [i+1][k] || [i][k-1] || [i][k+1]
