### ISSUE TITLE
Score System

### ISSUE THREAD

**Issue by aec1140** [CoffeeFrame/SNAIL#18]
A score system needs to be put into place. A global score property should be stored and should be incremented when circles are deleted.

See attached document, look for the part where drawHud is created, something similar should be done. 

[Boomshine-D.pdf](https://github.com/CoffeeFrame/SNAIL/files/979138/Boomshine-D.pdf)

**Comment by Awmusic12635** [comment]
In addition to that, we need some sort of end step or something to determine when it ends. 

Time based, score based , forever?

**Comment by aec1140** [comment]
See issue #19

**Comment by Awmusic12635** [comment]
Done in score_system branch
