### ISSUE TITLE
Max amount of moves

### ISSUE THREAD

**Issue by aec1140** [CoffeeFrame/SNAIL#19]
A max amount of moves should be in place and the game should stop when you run out of moves. 30 moves sounds good.

* [x] Create a GAME_STATE enum with....
    * BEGIN, DEFAULT, ROUND_OVER, END
*  [x] In init, set this.gameState to this.GAME_STATE.DEFAULT
*  [x] when max amount of moves has been reached, set gameState to this.GAME_STATE.END
*  [x] in mouseDown, if gameState == this.GAME_STATE.END you should return, as game is over

**Comment by Awmusic12635** [comment]
Is moves the best way to approach this? A few options, score based (score limit), time based, unlimited never ending.

**Comment by aec1140** [comment]
Moves is the best way in a week to complete

**Comment by Awmusic12635** [comment]
Done in score_system branch
